# config.py

# Descripciones por área
DESCRIPCIONES_AREAS = {
    "Video & Análisis": [
        "Creatividad / Proactividad.",
        "Toma de decisión / Resolución de problemas.",
        "Puntualidad y compromiso.",
        "Habilidades Comunicacionales.",
        "Jugadores, Staff, Extras.",
        "Trabajo en equipo, con pares, resto de staff.",
        "Comunicación Visual.",
        "Datos y estadísticas.",
        "Conocimiento del juego.",
        "Apto para resolver tecnología por fuera del video análisis.",
        "Captura de video - Real Time coding.",
    ],
    "Coaching": [
        "Explicación ejercicios, dinámica, utilización tiempo.",
        "Objetivo/s ejercicio.",
        "Corrección y transmisión.",
        "Retroalimentación (feedback).",
        "Toma de decisiones - resolución de problemas.",
        "Receptividad.",
        "Relacionamiento otros coaches, resto del staff y jugadores.",
        "Capacidad análisis equipo.",
        "Capacidad análisis durante partido.",
        "Capacidad análisis después partido.",
    ],
    "Fisio": [
        "Creatividad / Proactividad.",
        "Toma de decisión / Resolución de problemas.",
        "Puntualidad y compromiso.",
        "Habilidades Comunicacionales Jugadores, Staff, Extras.",
        "Trabajo en equipo, con pares, resto de staff.",
        "Organización y Planificación.",
        "Manejo de fisio rom, gimnasio y campo.",
        "Interpretación de la planificación.",
        "Manejo de herramientas tecnológicas, GPS, evaluaciones.",
        "Conocimiento del juego.",
    ],
    "Logística & Utilería": [
        "Trabajo en equipo.",
        "Planificación.",
        "Orden.",
        "Creatividad.",
        "Puntualidad.",
        "Toma de decisiones - resolución de problemas.",
        "Conocimiento del juego.",
        "Predisposición / Energía.",
        "Capacidad de trabajo y aprender.",
        "Proactivo.",
    ],
    "Match Official": [
        "Compromiso / Puntualidad.",
        "Nivel formación y experiencia previa.",
        "Planificación / planteo de objetivos.",
        "Trabajo en equipo, con pares, resto staff.",
        "Habilidades comunicacionales jugadores, staff, extras.",
        "Creatividad / Proactividad.",
        "Toma de decisiones / Resolución de problemas.",
        "Liderazgo de las actividades.",
        "Control y organización de las actividades y los tiempos de trabajo.",
        "Interpretación, análisis y uso de datos.",
    ],
    "Médico": [
        "Creatividad / Proactividad.",
        "Toma de decisiones / Resolución de problemas.",
        "Puntualidad / Compromiso.",
        "Habilidades Comunicacionales C/ Jugadores / Staff, etc.",
        "Trabajo en equipo con pares, resto del staff.",
        "Organización y Planificación.",
        "Manejo de fisio room, gimnasio y campo.",
        "Interpretación de la planificación.",
        "Manejo de herramientas tecnológicas, GPS, evaluaciones y revisión de video HIA.",
        "Conocimiento del juego.",
    ],
    "Preparación Física": [
        "Compromiso / Puntualidad.",
        "Nivel formación y experiencia previa.",
        "Planificación / Planteo de objetivos.",
        "Trabajo en equipo, con pares, resto staff.",
        "Habilidades comunicacionales jugadores, staff, extras.",
        "Creatividad / Proactividad.",
        "Toma de decisiones / Resolución de problemas.",
        "Liderazgo de las actividades.",
        "Control y organización de las actividades y los tiempos de trabajo.",
        "Interpretación, análisis y uso de datos.",
    ],
    "Team Manager": [
        "Compromiso / Puntualidad.",
        "Experiencia previa.",
        "Planificación / Planteo de objetivos.",
        "Trabajo en campo.",
        "Habilidades comunicacionales (jugadores, staff, extras).",
        "Creatividad / Proactividad.",
        "Toma de decisiones / Resolución de problemas.",
        "Liderazgo de las actividades.",
        "Trabajo en equipo, con pares, resto de staff.",
        "Control y organización de las actividades.",
    ],
    "Nutrición":[
        "Creatividad /Proactividad", 
        "Toma de decisión / Resolución de problemas", 
        "Gestión del tiempo y compromiso", 
        "Habilidades Comunicacionales Jugadores, Staff, Extras", 
        "Trabajo en equipo, con pares, resto de staff Nivel de formación en Nutrición Deportiva", 
        "Manejo protocolo ISAK 2 para medir", 
        "Interpretación antropométrica",
        "Manejo de herramientas tecnológicas, informáticas, etc.", 


    ],
}

# Diccionario de evaluadores por área
EVALUADORES_AREAS = {
    "Video & Análisis": "Martin Jauma",
    "Coaching": "D. Hourcade, L. Piña, P. Perez, R. Perez, R. Le Fort, Duran, P. Bouza, E. Meneses, Guzman.",
    "Fisio": "Lic. Martín Nuñez",
    "Logística & Utilería": "Javier Sorbera",
    "Match Official": "Juan Sylvestre",
    "Médico": "Dr. Juan Pablo Toledo",
    "Preparación Física": "Gonzalo Santos",
    "Team Manager": "Juan Manuel García",
    "Nutrición": "Lic. Romina Garavaglia",
}