# config.py

# Descripciones por área
#MAJ Aca tenemos todas los detalles de la evaluacion, si quiero hacer alguna cambio es aca
DESCRIPCIONES_AREAS = {
    "Video & Análisis": [
        "Creatividad / Proactividad.",
        "Toma de decisión / Resolución de problemas.",
        "Puntualidad y compromiso.",
        "Habilidades Comunicacionales.",
        "Trabajo en equipo, con pares, resto de staff.",
        "Comunicación Visual.",
        "Datos y estadísticas.",
        "Conocimiento del juego.",
        "Apto para resolver tecnología por fuera del video análisis.",
        "Captura de video - Real Time coding.",
    ],
    "Coaching": [
        "Explicación ejercicios, dinámica, utilización tiempo.",
        "Objetivo/s ejercicio.",
        "Corrección y transmisión.",
        "Retroalimentación (feedback).",
        "Toma de decisiones - resolución de problemas.",
        "Receptividad.",
        "Relacionamiento otros coaches, resto del staff y jugadores.",
        "Capacidad análisis equipo.",
        "Capacidad análisis durante partido.",
        "Capacidad análisis después partido.",
    ],
    "Fisio": [
        "Creatividad / Proactividad.",
        "Toma de decisión / Resolución de problemas.",
        "Puntualidad y compromiso.",
        "Habilidades Comunicacionales Jugadores, Staff, Extras.",
        "Trabajo en equipo, con pares, resto de staff.",
        "Organización y Planificación.",
        "Manejo de fisio rom, gimnasio y campo.",
        "Interpretación de la planificación.",
        "Manejo de herramientas tecnológicas, GPS, evaluaciones.",
        "Conocimiento del juego.",
    ],
    "Logística & Utilería": [
        "Trabajo en equipo.",
        "Planificación.",
        "Orden.",
        "Creatividad.",
        "Puntualidad.",
        "Toma de decisiones - resolución de problemas.",
        "Conocimiento del juego.",
        "Predisposición / Energía.",
        "Capacidad de trabajo y aprender.",
        "Proactivo.",
    ],
    "Match Official": [
        "Compromiso / Puntualidad.",
        "Objetivo/s personales de la capacitación.",
        "Demostración de herramientas para la conducción del juego",
        "Retroalimentación  (feedback)",
        "Toma de decisiones - resolución de problemas.",
        "Receptividad.",
        "Relacionamiento otros coache , resto del staff y jugadores",
        "Capacidad análisis equipo.",
        "Capacidad análisis durante partido.",
        "Capacidad análisis después partido.",
    ],
    "Médico": [
        "Creatividad / Proactividad.",
        "Toma de decisiones / Resolución de problemas.",
        "Puntualidad / Compromiso.",
        "Habilidades Comunicacionales C/ Jugadores / Staff, etc.",
        "Trabajo en equipo con pares, resto del staff.",
        "Organización y Planificación.",
        "Manejo de fisio room, gimnasio y campo.",
        "Interpretación de la planificación.",
        "Manejo de herramientas tecnológicas, GPS, evaluaciones y revisión de video HIA.",
        "Conocimiento del juego.",
    ],
    "Preparación Física": [
        "Compromiso / Puntualidad.",
        "Nivel formación y experiencia previa.",
        "Planificación / Planteo de objetivos.",
        "Trabajo en equipo, con pares, resto staff.",
        "Habilidades comunicacionales jugadores, staff, extras.",
        "Creatividad / Proactividad.",
        "Toma de decisiones / Resolución de problemas.",
        "Liderazgo de las actividades.",
        "Control y organización de las actividades y los tiempos de trabajo.",
        "Interpretación, análisis y uso de datos.",
    ],
    "Team Manager": [
        "Compromiso / Puntualidad.",
        "Experiencia previa.",
        "Planificación / Planteo de objetivos.",
        "Trabajo en campo.",
        "Habilidades comunicacionales (jugadores, staff, extras).",
        "Creatividad / Proactividad.",
        "Toma de decisiones / Resolución de problemas.",
        "Liderazgo de las actividades.",
        "Trabajo en equipo, con pares, resto de staff.",
        "Control y organización de las actividades.",
    ],
    "Nutrición":[
        "Creatividad /Proactividad", 
        "Toma de decisión / Resolución de problemas", 
        "Gestión del tiempo y compromiso", 
        "Habilidades Comunicacionales Jugadores, Staff, Extras", 
        "Trabajo en equipo, con pares, resto de staff", 
        "Nivel de formación en Nutrición Deportiva", 
        "Manejo protocolo ISAK 2 para medir", 
        "Interpretación antropométrica",
        "Manejo de herramientas tecnológicas, informáticas, etc.",
        "Conocimiento del juego y de preparación física",

    ],
}

DESCRIPCIONES_AREAS_EN = {
    "Video & Análisis": [
        "Creativity / Proactivity.",
        "Decision making / Problem solving.",
        "Punctuality and commitment.",
        "Communication skills.",
        "Teamwork, with peers, other staff.",
        "Visual communication.",
        "Data and statistics.",
        "Knowledge of the game.",
        "Able to solve technology outside of video analysis.",
        "Video capture - Real Time coding.",
    ],
    "Coaching": [
        "Exercise explanation, dynamics, time utilization.",
        "Exercise objective(s).",
        "Correction and transmission.",
        "Feedback.",
        "Decision making - problem solving.",
        "Receptivity.",
        "Relationship with other coaches, other staff and players.",
        "Team analysis capacity.",
        "Analysis capacity during the match.",
        "Analysis capacity after the match.",
    ],
    "Fisio": [
        "Creativity / Proactivity.",
        "Decision making / Problem solving.",
        "Punctuality and commitment.",
        "Communication skills with Players, Staff, Extras.",
        "Teamwork, with peers, other staff.",
        "Organization and Planning.",
        "Management of physio room, gym and field.",
        "Interpretation of planning.",
        "Management of technological tools, GPS, evaluations.",
        "Knowledge of the game.",
    ],
    "Logística & Utilería": [
        "Teamwork.",
        "Planning.",
        "Order.",
        "Creativity.",
        "Punctuality.",
        "Decision making - problem solving.",
        "Knowledge of the game.",
        "Predisposition / Energy.",
        "Ability to work and learn.",
        "Proactive.",
    ],
    "Match Official": [
        "Commitment / Punctuality.",
        "Personal training objective(s).",
        "Demonstration of tools for game management.",
        "Feedback.",
        "Decision making - problem solving.",
        "Receptivity.",
        "Relationship with other coaches, other staff and players.",
        "Team analysis capacity.",
        "Analysis capacity during the match.",
        "Analysis capacity after the match.",
    ],
    "Médico": [
        "Creativity / Proactivity.",
        "Decision making / Problem solving.",
        "Punctuality / Commitment.",
        "Communication skills with Players / Staff, etc.",
        "Teamwork with peers, other staff.",
        "Organization and Planning.",
        "Management of physio room, gym and field.",
        "Interpretation of planning.",
        "Management of technological tools, GPS, evaluations and HIA video review.",
        "Knowledge of the game.",
    ],
    "Preparación Física": [
        "Commitment / Punctuality.",
        "Level of training and previous experience.",
        "Planning / Setting objectives.",
        "Teamwork, with peers, other staff.",
        "Communication skills with players, staff, extras.",
        "Creativity / Proactivity.",
        "Decision making / Problem solving.",
        "Leadership of activities.",
        "Control and organization of activities and work times.",
        "Interpretation, analysis and use of data.",
    ],
    "Team Manager": [
        "Commitment / Punctuality.",
        "Previous experience.",
        "Planning / Setting objectives.",
        "Field work.",
        "Communication skills (players, staff, extras).",
        "Creativity / Proactivity.",
        "Decision making / Problem solving.",
        "Leadership of activities.",
        "Teamwork, with peers, other staff.",
        "Control and organization of activities.",
    ],
    "Nutrición":[
        "Creativity / Proactivity",
        "Decision making / Problem solving",
        "Time management and commitment",
        "Communication skills with Players, Staff, Extras",
        "Teamwork, with peers, other staff",
        "Level of training in Sports Nutrition",
        "Management of ISAK 2 protocol for measurement",
        "Anthropometric interpretation",
        "Management of technological, computer, etc. tools.",
        "Knowledge of the game and physical preparation",
    ],
}
#MAJ Este diccionario es para poner en AREA y el Evaluador de esa Area
# Diccionario de evaluadores por área
EVALUADORES_AREAS = {
    "Coaching": "D. Hourcade, L. Piña, P. Perez, R. Perez, R. Le Fort, Duran, P. Bouza, E. Meneses, Guzman.",
    "Fisio": "Lic. Martín Nuñez",
    "Logística & Utilería": "Javier Sorbera",
    "Match Official": "Juan Sylvestre",
    "Médico": "Dr. Juan Pablo Toledo",
    "Nutrición": "Lic. Romina Garavaglia",
    "Preparación Física": "Gonzalo Santos",
    "Team Manager": "Juan Manuel García",
    "Video & Análisis": "Martín Jauma",   
}