[mongo_uri] = "mongodb+srv://<username>:<password>@<cluster-url>/"
[db_name] = "SAR"
[collection_name] = "evaluaciones_data"

[gcp_project_id] = "your-gcp-project-id"
[google_api_key] = "AIzaSyBIDOkAQ6glvWsIZkkppyPB8ecqR1c3yx8"